# Generated by Django 5.1.4 on 2025-01-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Equipe")),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.CreateModel(
            name="Prestador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("Limpeza Residencial", "Limpeza Residencial"),
                            ("Manutenção Elétrica", "Manutenção Elétrica"),
                            ("Reformas", "Reformas"),
                            ("Jardinagem", "Jardinagem"),
                            ("Aulas Particulares", "Aulas Particulares"),
                            ("Cuidador de Idosos", "Cuidador de Idosos"),
                            ("Consultoria", "Consultoria"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Serviço",
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço (R$)"
                    ),
                ),
                (
                    "modalidade_preco",
                    models.CharField(
                        choices=[
                            ("por hora", "Por Hora"),
                            ("serviço completo", "Serviço Completo"),
                        ],
                        default="por hora",
                        max_length=20,
                        verbose_name="Modalidade de Preço",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "foto",
                    models.ImageField(
                        upload_to="fotos_prestadores/", verbose_name="Foto do Prestador"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Prestador",
                "verbose_name_plural": "Prestadores",
            },
        ),
        migrations.CreateModel(
            name="Trabalho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=150, verbose_name="Título do Trabalho"),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("Limpeza Residencial", "Limpeza Residencial"),
                            ("Manutenção Elétrica", "Manutenção Elétrica"),
                            ("Reformas", "Reformas"),
                            ("Jardinagem", "Jardinagem"),
                            ("Aulas Particulares", "Aulas Particulares"),
                            ("Cuidador de Idosos", "Cuidador de Idosos"),
                            ("Consultoria", "Consultoria"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Serviço",
                    ),
                ),
                (
                    "preco_oferecido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Preço Oferecido (R$)",
                    ),
                ),
                (
                    "modalidade_preco",
                    models.CharField(
                        choices=[
                            ("por hora", "Por Hora"),
                            ("serviço completo", "Serviço Completo"),
                        ],
                        default="por hora",
                        max_length=20,
                        verbose_name="Modalidade de Preço",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição do Trabalho")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Trabalho",
                "verbose_name_plural": "Trabalhos",
            },
        ),
    ]
