# Generated by Django 5.0.7 on 2025-01-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biko_job", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Prestador",
        ),
        migrations.DeleteModel(
            name="Trabalho",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
