# Generated by Django 5.0.7 on 2025-01-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biko_job", "0004_user_delete_customuser"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
