# Generated by Django 5.0.7 on 2025-01-13 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biko_job", "0005_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_servico", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "modalidade_preco",
                    models.CharField(
                        choices=[
                            ("por hora", "Por Hora"),
                            ("serviço completo", "Serviço Completo"),
                        ],
                        default="por hora",
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="prestadores/fotos/"
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
