# Generated by Django 5.0.7 on 2025-01-14 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biko_job", "0006_prestador"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_servico", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "modalidade_preco",
                    models.CharField(
                        choices=[
                            ("por hora", "Por Hora"),
                            ("serviço completo", "Serviço Completo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField()),
                ("foto", models.ImageField(upload_to="servicos/")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Prestador",
        ),
    ]
