# Generated by Django 5.1.4 on 2025-01-20 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biko_job", "0009_agendamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamento",
            name="trabalho",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="concluido",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="servico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="biko_job.servico",
            ),
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pontualidade", models.IntegerField()),
                ("qualidade", models.IntegerField()),
                ("comunicacao", models.IntegerField()),
                ("custo_beneficio", models.IntegerField()),
                ("profissionalismo", models.IntegerField()),
                ("media", models.FloatField(editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_feitas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prestador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_recebidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Trabalho",
        ),
    ]
