# Generated by Django 5.1.4 on 2025-01-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biko_job", "0010_remove_agendamento_trabalho_agendamento_concluido_and_more"),
    ]

    operations = []
