# Generated by Django 5.1.4 on 2025-01-21 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biko_job", "0011_auto_20250121_2005"),
    ]

    operations = [
        migrations.AddField(
            model_name="avaliacao",
            name="servico",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="biko_job.servico",
            ),
            preserve_default=False,
        ),
    ]
